version: '3'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: tests    
        ports:
            - 3366:3366    
        networks: 
            - app
        volumes: 
            - ./postgres:/var/lib/postgres
    node: 
        build: 
            context: .
            dockerfile: nodejs-docker/Dockerfile
        volumes: 
            - ./:/usr/src/app
        networks: 
            - app
        depends_on: 
            - db
        ports:
            - "3000:3000"
networks:
    app: